"""initial migration

Revision ID: 836617435f51
Revises: 
Create Date: 2019-11-24 20:22:58.538066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836617435f51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=16), nullable=True),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('birth', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=32), nullable=True),
    sa.Column('class_name', sa.String(length=32), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_index(op.f('ix_students_phone_number'), 'students', ['phone_number'], unique=True)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_phone_number'), table_name='students')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
